theme: jekyll-theme-minimal
title: <div align="center"><img src="images/photo.jpg" width="150"/></div>
description: Solving challenging large-scale problems at ease with Decision Optimization. Cheering up meetings through judicious use of memes.
